from sqlalchemy.orm import Session
import json, re
import logging

from app.workers.celery_app import celery_app
from app.db.session import SessionLocal
from app.db import models
from app.llm.client import generate_chat
from app.llm.prompts import OUTLINE_PROMPT
from app.utils.redis_pub import publish_event

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

CORE_SECTIONS = [
    "Problem Context & Validation",
    "Target Users & Personas",
    "Existing Solutions",
    "Competitor Landscape",
    "Market & Industry Trends",
    "Opportunities & Gaps",
    "Risks & Open Questions",
]

ALLOWED_OPTIONAL_SECTIONS = {
    "Technical Feasibility",
    "Regulatory Considerations",
    "Go-To-Market Strategy",
}

@celery_app.task(bind=True)
def run_outline(self, report_id: str):
    """
    TODO:
    1. Load report
    2. Load session.clarified_summary
    3. Validate clarified_summary exists
    4. Call LLM to generate outline
    5. Parse + normalize section titles
    6. Delete existing sections (idempotent)
    7. Insert ordered sections
    8. Publish outline_ready SSE event
    """
    db: Session = SessionLocal()

    try:
        report = db.query(models.Report).filter_by(id=report_id).first()
        if not report:
            raise ValueError("Report not found")

        session = db.query(models.Session).filter_by(id=report.session_id).first()
        if not session or not session.clarified_summary:
            raise ValueError("Clarified summary missing")

        # -------------------------------
        # Call LLM
        # -------------------------------
        prompt = OUTLINE_PROMPT.replace(
            "{{CLARIFIED_SUMMARY}}",
            session.clarified_summary
        )

        def _generate_and_parse(system_prompt: str) -> list[str]:
            raw_output = generate_chat(
                messages=[{"role": "system", "content": system_prompt}],
                temperature=0.2,
                task="outline",
            )
            return parse_outline(raw_output)

        # LLM JSON reliability plan §4: same one-shot repair retry as
        # clarification_worker.py / section_worker.py / verdict_worker.py --
        # outline_failed is a fatal, session-ending event (see
        # orchestrator_service.py), so a single non-retryable Groq failure
        # (RuntimeError) or malformed output (ValueError from parse_outline)
        # shouldn't kill the run without one retry.
        try:
            section_titles = _generate_and_parse(prompt)
        except (ValueError, RuntimeError) as exc:
            logger.info(
                "[OUTLINE] Repairing failed draft report_id=%s reason=%s",
                report_id,
                exc,
            )
            repair_prompt = (
                prompt
                + "\n\nREPAIR REQUIRED:\n"
                + f"{exc}\n"
                + "Regenerate the full JSON so the outline is valid."
            )
            section_titles = _generate_and_parse(repair_prompt)

        # -------------------------------
        # Idempotent persistence
        # -------------------------------
        db.query(models.Section).filter_by(report_id=report_id).delete()

        section_rows = []
        for idx, title in enumerate(section_titles, start=1):
            section = models.Section(
                report_id=report_id,
                title=title,
                order_index=idx,
            )
            db.add(section)
            section_rows.append(section)

        # Flush so autogenerated section ids are populated BEFORE we build the
        # event payload (B2.3 — avoids null section_id in outline_ready).
        db.flush()

        sections = [
            {
                "section_id": section.id,
                "title": section.title,
                "order_index": section.order_index,
            }
            for section in section_rows
        ]

        db.commit()

        # -------------------------------
        # Emit event
        # -------------------------------
        publish_event(
            "outline_ready",
            {
                "report_id": report_id,
                "sections": sections,
            }
        )

    except Exception as e:
        publish_event(
            "outline_failed",
            {"report_id": report_id, "error": str(e)},
        )
        raise

    finally:
        db.close()

    
    
# LLM OUTPUT (UNTRUSTED) -> PARSING    
def parse_outline(raw_output: str) -> list[str]:
    """
    Parse STRICT JSON output from LLM.
    Enforce core sections + limit optional sections.
    """
    try:
        data = json.loads(raw_output)
    except json.JSONDecodeError:
        raise ValueError("Outline LLM output is not valid JSON")

    sections = data.get("sections")
    if not isinstance(sections, list) or not sections:
        raise ValueError("Missing or invalid 'sections' array")

    cleaned = []
    seen = set()

    # Enforce core sections first (deterministic)
    for core in CORE_SECTIONS:
        cleaned.append(core)
        seen.add(core.lower())

    # Add optional sections from LLM output
    for title in sections:
        if not isinstance(title, str):
            continue

        key = title.strip().lower()
        if key in seen:
            continue

        if title in ALLOWED_OPTIONAL_SECTIONS:
            cleaned.append(title)
            seen.add(key)

        if len(cleaned) >= len(CORE_SECTIONS) + 3:
            break

    return cleaned
